### ISSUE TITLE
Error setting height and width for keras_hub.models.StableDiffusion3TextToImage.from_preset

### ISSUE THREAD

**Issue by marciofreire** [keras-team/keras-hub#1957] opened 2024-10-26 01:00 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Additional context**

**Would you like to help us fix it?**
I wish I had this knowledge.

**Comment by james77777778** [comment] 2024-10-26 07:57
Hey @marciofreire 
Could you provide a reproducible script for this bug?
We recently changed the parameter signature for the consistency across models. If you're using the latest version of KerasHub, you should be able to instantiate SD3 like this:

```python
text_to_image = StableDiffusion3TextToImage.from_preset(
    "stable_diffusion_3_medium",
    image_shape=(height, width, 3),
    dtype="float16",
)
```

**Comment by divyashreepathihalli** [comment] 2024-11-02 00:09
Great!! Since the issue was resolved, I will close the issue.

**Closed by divyashreepathihalli** 2024-11-02 00:09 UTC
